DeliX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('home.urls', namespace='home')),
    path('orgs/', include('organizations.urls', namespace='organizations')),
    path('topics/', include('topics.urls', namespace='topics')),
    path('activities/',include('activities.urls', namespace='activities')),
    path('select2/', include('django_select2.urls')),
     ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('home/', views.index, name='index'),

]

organizations/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.decorators import login_required

app_name = "organizations"

urlpatterns = [
    # path('', views.IndexView.as_view(), name='<slug>.index'),

    path('', views.index, name = "index"),
    path('register/new_org/', views.RegisterView.as_view(), name = "register"),
    #path('<slug:org_slug>/', views.specific_org, name = "specific_org"),
    path('<slug:org_slug>/', views.OrgDetail.as_view(), name = "specific_org"),

    #to detail of tags
    path('<slug:org_slug>/tags/', views.OrgTagList.as_view(), name = "specific_org_tags"),

    path('<slug:org_slug>/', include('topics.urls', namespace = "specific_org_topics")),

    path('<slug:org_slug>/campaigns/', include('campaign.urls', namespace = 'org_campaigns')),
    path('<slug:org_slug>/join/', login_required(views.join), name='join'),
    ]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('register/org', views.RegisterOrgView.as_view(), name='org_register'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', views.logout_view, name='logout'),
    path('org_autocomplete/', views.OrgAutocomplete.as_view(), name='org_autocomplete'),
    path('<slug:username>/profile/', views.UserDetail.as_view(), name ='user_profile'),
    path('<slug:username>/profile/update/', views.UpdateProfileView.as_view(), name ='profile_update'),

]

organizations/models.py
# Create your models here.
from django.db import models
# Create your models here.
import uuid
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from taggit.managers import TaggableManager
from django.conf import settings
from topictag.models import TaggedObject, Tag
from django.contrib.auth import get_user_model
User = get_user_model()


class Organization(models.Model):
    name = models.CharField(max_length= 255)
    location_street = models.CharField(max_length = 255)
    location_city = models.CharField(max_length = 255)
    location_state = models.CharField(max_length = 255)
    location_country = models.CharField(max_length = 255)
    location_ZIP = models.IntegerField()
    summary = models.TextField()
    created_date = models.DateTimeField('Created date', auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

    org_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    active  = models.BooleanField(default=False) #need verification
    confirmed_identity = models.BooleanField(default=False)
    government = models.BooleanField(default = False)
    private = models.BooleanField(default=False)

    #decision_makers = models.ManyToManyField(User, related_name='+')
    #constituent = models.ManyToManyField(User, related_name='+')
    #username_field and password are required by default

    # objects = OrganizationManager()

    tags = TaggableManager(through=TaggedObject)


    def get_tag_names(self):
        return [tag.name for tag in Tag.objects.get_for_object(self)]

    def get_name(self):
        return self.name
    #property
    def is_government(self):
        return self.government
    def is_private(self):
        return self.private
    def is_active(self):
        return self.active
    def is_confirmed_identity(self):
        return self.confirmed_idenity

    org_slug = models.SlugField(max_length=250, unique=True)

    def save(self, *args, **kwargs):
        self.org_slug = slugify(self.name)
        super(Organization, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('organizations:specific_org', kwargs={'org_slug' : self.org_slug})
    def get_tag_list_url(self):
        return reverse('organizations:specific_org_tags', kwargs={'org_slug' : self.org_slug})


    #add in org_type, adding additional files of org
    # org_model = models.ForeignKey(OrgModel, on_delete=models.CASCADE)

    ORG_TYPE_CHOICES = (
        (0, 'not specified'),
        (1, 'city'),
        (2, 'state'),
        (3, 'federal'),
        (4, 'agency'),
        (5, 'department'),
        (6, 'company'),
        (7, 'house'),
        (8, 'school'),
    )

    org_type = models.PositiveSmallIntegerField(choices=ORG_TYPE_CHOICES, blank=True, default = 0)
    members = models.ManyToManyField(User, blank=True, related_name='orgs')    
# class Member(models.Model):
#     member = models.ForeignKey(User, related_name='members', on_delete=models.CASCADE,)
#     organization = models.ForeignKey(Organization, related_name='organizations', on_delete=models.CASCADE,)
    
#     class Meta:
#         unique_together = ('member', 'organization')

#     def __unicode__(self):
#         return u'%s is member of %s' % (self.member, self.organization)

class OrgProfile(models.Model):
    pass

class CommunityWiki(models.Model):

    pass

# class OrgModel(models.Model):
#     org_type = models.CharField(max_length=255, blank = True)
#     org_type_description = models.TextField(blank=True)
#     org_files = models.



# class OrgMembership(models.Model):
#     membership_type = models.CharField(max_length=255, blank=True)
#     membership_type_description = models.TextField(blank=True)
#     ass_model = models.ForeignKey(OrgModel)
#     member = models.ForeignKey( related_name="org_member", on_delete=models.CASCADE, blank = True, null = True)


#     roles = models.CharField(max_length=255, blank = True)
#     hierch_0 = models.BooleanField(default=True) #observer
#     hierch_1 = models.BooleanField(default=False) #member
#     hierch_2 = models.BooleanField(default=False) # staff
#     hierch_3 = models.BooleanField(default=False) # DeliDeX's specific org's managers

#go wth:
# class OrgMember:
#   permission= 
#class OrgAdmin:
#   permission= ....
#hardcode for now
# class Role(models.Model):
#   '''
#   The Role entries are managed by the system,
#   automatically created via a Django data migration.
#   '''
#   STUDENT = 1
#   TEACHER = 2
#   SECRETARY = 3
#   SUPERVISOR = 4
#   ADMIN = 5
#   ROLE_CHOICES = (
#       (STUDENT, 'student'),
#       (TEACHER, 'teacher'),
#       (SECRETARY, 'secretary'),
#       (SUPERVISOR, 'supervisor'),
#       (ADMIN, 'admin'),
#   )

#   id = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

#   def __str__(self):
#       return self.get_id_display()

# class OrgMember(models.Model):

organizations/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate
from .models import Organization
from taggit.forms import *
#
# class OrgAddTagForm(forms.Form):
#     name = forms.CharField()
#     m_tags = TagField()

class OrgAddTagForm(forms.Form):
    tag = forms.CharField(label='Tag', max_length=100)

    # class Meta:
    #     model = Organization
    #     field = 'tags'


class RegisterForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ('name','location_street', 'location_city',
                'location_state', 'location_country', 'location_ZIP', 'org_type',
                  )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        qs = Organization.objects.filter(name=name)
        if qs.exists():
            raise forms.ValidationError("Organization may have already been registered")
        return name

    def save(self, commit=True):
        organization = super(RegisterForm, self).save(commit=False)
        organization.confirmed_identity = False #need confirmation email
        if commit:
            organization.save()
        return organization



#class RegisterImpact(forms.ModelForm):
#   add autocomplete: select2 widget


# class OrgRoleCreateForm(models.ModelForm):
#     class Meta:
#         model = OrgRole

#         def save(self,commit=True):
#             orgrole= super(OrgRoleCreateForm, self).save(commit=False)
#             if commit:
#                 orgrole.save()
#             return orgrole

organizations/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Organization
# Create your views here.
#from topics.models import Topic
from django.views.generic import DetailView, ListView
from django.shortcuts import render
from django.views.generic import CreateView, FormView, UpdateView
from .forms import RegisterForm, OrgAddTagForm
from django.urls import reverse_lazy
from django.shortcuts import redirect


#
# class OrganizationView(DetailView):
#     model = Organization
#     template_name = "organizations/specific_org.html"
#     context_object_name = 'org'
#
#     slug_field = "org_slug"
#     slug_url_kwarg = "org_slug"



    #
    # paginate_by = 10
    # queryset = Organization.objects.filter(name="Cloyne")
    # context_object_name = "organization_list"


    # organization = Organization.objects.filter(name=slug_field)
    # def get_queryset(self):
    #     queryset = (Topic.objects
    #                 .filter(organization.name = self.slug_field)
    #
    #                 .order_by('-created_date'))
    #     child.name for child in obj.children.all()
    #
    #     return queryset

def index(request):
    context = {'orgs': Organization.objects.all(),
    # 'orgs_sorted_tags': Organization.objects.filter(tags__name__in=["laundry", ]).distinct(),
    #'user_org': Organization.objects.filter(user = request.user),
    # 'user_membership': request.user.usermembership_set.all(),
               }
    return render(request, 'organizations/index.html', context)


class RegisterView(CreateView):
   form_class = RegisterForm
   template_name = "organizations/registration.html"
   success_url = reverse_lazy('organizations:index')
   context = {
      'form': RegisterForm()
   }

def specific_org(request, org_slug):
    context = {'org': Organization.objects.get(org_slug=org_slug),
               'impacts': Organization.objects.get(org_slug=org_slug).org_impacts.all(),
               }

        # return self.render_to_response(self.get_context_data())
    
def join(request, org_slug):
    user = request.user
    org = Organization.objects.get(org_slug=org_slug)
    org.members.add(user)
    org.save()
    return redirect(org)


# def unjoin(request, target_id):
#     follow = Follow.objects.filter(user=request.user, target_id=target_id).first()
#     if follow is not None:
#         follow.delete()
#     return redirect("/")

class OrgDetail(DetailView):
    model = Organization
    template_name = 'organizations/specific_org.html'
    slug_field = "org_slug"
    slug_url_kwarg = "org_slug"
    # This was my attempt to work it into the View...
    def post(self, request, *args, **kwargs):
        organization = self.get_object()  ###suspect wth the slug and self.get_object
        form = OrgAddTagForm(request.POST)
        if form.is_valid():
            organization.tags.add(form.cleaned_data['tag'])
        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        org_slug = self.kwargs.get('org_slug')
        self.object = self.get_object()
        context = super(OrgDetail, self).get_context_data(**kwargs)

        context = {'org': Organization.objects.get(org_slug=org_slug),
                   #'impacts': Organization.objects.get(org_slug=org_slug).org_impacts.all(),
                   'form': OrgAddTagForm(),
                   }
        return context
class OrgTagList(DetailView):
    # queryset = Organization
    # def get_queryset(self):  #(self, **kwargs):
    #     queryset =
    #     # if self.request.GET.get("browse"):
    #     #     selection = self.request.GET.get("browse")
    #     #     if selection == "Cats":
    #     #         queryset = Cats.objects.all()
    #     org_slug = self.kwargs.get('org_slug')
    #     self.object = self.get_object()
    #     context = super().get_context_data(**kwargs)
    #     context['org'] = Organization.objects.get(org_slug=org_slug)
    #     return queryset
    model = Organization
    template_name = 'organizations/specific_org_tag_list.html'

    slug_field = "org_slug"
    slug_url_kwarg = "org_slug"

    # This was my attempt to work it into the View...

    def get_context_data(self, **kwargs):
        org_slug = self.kwargs.get('org_slug')
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        context = {'org': Organization.objects.get(org_slug=org_slug),
                   # 'impacts': Organization.objects.get(org_slug=org_slug).org_impacts.all(),
                   'form': OrgAddTagForm(),
                   }
        return context


#
# class OrgTagDetail(DetailView):
#     def get_object(self):
#         org_slug = self.kwargs.get('organiser')
#         tag_slug = self.kwargs.get('event')

organizations/templates/organizations/contact.html
{% extends 'base_home.html' %}

{% block content %}
	<p style="font-size:69">CONTACT ME MAYBE!</p>
	<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>


<h3>Contact Form</h3>

<div class="container">
  <form action="/action_page.php">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

organizations/templates/organizations/index.html
{% extends 'base_home.html' %}

{% block content %}
	


	<p>My communities</p>
	
	{% for o in request.user.orgs.all %}
        <a href="{% url 'organizations:specific_org' org_slug=o.org_slug %}">{{ o.name }}
        </a>        
        {% endfor %}


	<p>Other groups near me</p>
		{% for org in orgs %}
		{% if org not in request.user.orgs.all %}
	<a href="{{ org.get_absolute_url }}">{{ org.name }}</a>
		{% endif %}
		{% endfor %} 

	<br>
	<p>
		<a href="{% url 'organizations:register' %}">Register new organization</a>
	</p>

{% endblock %}

organizations/templates/organizations/registration.html
{% extends "base_home.html" %}
{% block content %}
<!-- Form - User -->
<div id="register">
    
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
   
        </style>
        {{ form.as_p }}
        <hr>
        <button type="submit" class="registerbtn">Register</button>
        
    </form>
</div>
{% endblock content %}

organizations/templates/organizations/specific_org.html
{% extends 'base_home.html' %}

{% block breadcrumb %}
<a href="{% url 'organizations:specific_org' org_slug=org.org_slug %}" >{{org.name}}</a>

{% endblock %}

{% block content %}

<p>


{% if request.user in org.members.all %}
 {% else %}
 <a href="{% url 'organizations:join' org_slug=org.org_slug %}">Join as a member</a>
  {% endif %}
</a>
</p>

<div class="section">
    <div class="i1section">
        <div class="section_header">
            {{ org.name }}
        </div>
        <ul>
           
            <li><a href="https://localwiki.org/ ">Learn more on LocalWiki!</a>
            </li>
            <li>
                <div class="add-tag-form">
                    <form method="POST" class="post-form">{% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="save btn btn-default btn-sm">Add</button>
                    </form>
                </div>
            </li>

            <li>
              <p>
                List of members:
  {% for m in org.members.all %}
  <a href = "{% url 'users:user_profile' username=m.username %}">{{ m.username }}</a>

        
  {% endfor %}
              </p>
              {% for member in membership %}
      <a href="{% url 'users:user_profile' username=member.user.username %}">{{member.user.username}}</a>
    {% endfor %}
            </li>
        </ul>
    </div>

    <div class = "i2section">
      <h3>Ongoing votes</h3>
    </div>
    <ul>
      <li>
  <a href="{% url 'organizations:org_campaigns:create_campaign' org_slug=org.org_slug %}">Create new campaign
  </a>
      </li>
      <li>
        {% for campaign in org.campaigns.all %}
    <div class="outcome_columns">
  <ul class="outcome">
    <li class="header"><a href="{{ campaign.get_absolute_url_mod }}">{{ campaign.name }}</a>
</li>
    <li class="grey">Date logged: {{campaign.created_date|date }}</li>
    <li>Ongoing: 
      {% if campaign.active == True %} &#10004;qe
      {% else %} &times;
      {% endif %}</li>
    <li>Summary: {{ campaign.summary }}</li>
    <li>Members following: </li>

  </ul>
</div>


    {% endfor %}
      </li>
    </ul>
</div>




<div id = "list_of_topics">
<div class="row">
  

    {% for topic in org.organization_topics.all %}
    <div class="outcome_columns">
  <ul class="outcome">
    <li class="header"><a href="{{ topic.get_absolute_url_mod }}">{{ topic.name }}</a>
</li>
    <li class="grey">Date logged: {{topic.created_date|date }}</li>
    <li>Ongoing: 
      {% if topic.active == True %} &#10004;qe
      {% else %} &times;
      {% endif %}</li>
    <li>Deliberating members: </li>
    <li>Summary: {{ topic.summary }}</li>
    <li>Current sentiment: (pie chart of % of words from public adoped, % of words/proposals from experts/officials adopted)</li>
    <li>Timeline: </li>
    <li>Most recent activity: </li>
    <li>Pros and cons</li>
    <li class="grey"><a href="#" class="button">Do something?</a></li>
  </ul>
</div>


    {% endfor %}
    <br>



</div>
</div>
<h3>Reminders</h3>
<h2>Archived Campaigns</h2>
{% for t in topic_archived %}
{{ t.name }}
{% endfor %}
<h4>Activities</h4>
<h4>List of members</h4>
    {% for member in membership %}
      <a href="{% url 'users:user_profile' username=member.user.username %}">{{member.user.username}}</a>
    {% endfor %}
{% endblock %}

organizations/templates/organizations/specific_org_tag_list.html
{% extends 'base_organizations.html' %}

{% block content %}

<h1>
  How {{ org.name }} affects you:
</h1>
    <div id="tag_label">


    {% for tag in org.tags.all %}

    <a href="#">{{ tag.name }}</a>
        {% endfor %}
    </div>
    <div class="add-tag-form">
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default btn-sm">Add</button>
        </form>
    </div>


<h3>Reminders</h3>
<h3>Activities</h3>
{% endblock %}