DeliX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('home.urls', namespace='home')),
    path('orgs/', include('organizations.urls', namespace='organizations')),
    path('topics/', include('topics.urls', namespace='topics')),
    path('activities/',include('activities.urls', namespace='activities')),
    path('select2/', include('django_select2.urls')),
     ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('home/', views.index, name='index'),

]

organizations/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.decorators import login_required

app_name = "organizations"

urlpatterns = [
    # path('', views.IndexView.as_view(), name='<slug>.index'),

    path('', views.index, name = "index"),
    path('register/new_org/', views.RegisterView.as_view(), name = "register"),
    #path('<slug:org_slug>/', views.specific_org, name = "specific_org"),
    path('<slug:org_slug>/', views.OrgDetail.as_view(), name = "specific_org"),

    #to detail of tags
    path('<slug:org_slug>/tags/', views.OrgTagList.as_view(), name = "specific_org_tags"),

    path('<slug:org_slug>/', include('topics.urls', namespace = "specific_org_topics")),

    path('<slug:org_slug>/campaigns/', include('campaign.urls', namespace = 'org_campaigns')),
    path('<slug:org_slug>/join/', login_required(views.join), name='join'),
    ]

topics/urls.py
from django.urls import path, include
from . import views

app_name = "topics"

urlpatterns = [
    # path('', views.IndexView.as_view(), name='<slug>.index'),

    path('', views.index, name = "index"),
    path('topics/create_new/', views.RegisterTopicView.as_view(), name = "create_topic"),
    #path('<slug:topic_slug>/', views.specific_topic, name = "specific_topic"),

    #path('topics/<slug:topic_slug>/', views.specific_topic, name= "org_topic"),
    path('topics/<slug:topic_slug>/', views.TopicDetail.as_view(), name="org_topic"),
    path('topics/<slug:topic_slug>/outcomes/', views.TopicOutcomes.as_view(), name="topic_outcomes"),
    path('topics/<slug:topic_slug>/explore/', views.TopicExplore.as_view(), name="topic_explore"),
    path('topics/<slug:topic_slug>/', include('activities.urls', namespace="specific_topic_act")),

    path('topics/', views.list_topics, name="org_list_topics"),

    # path('<org_slug:org_slug>/', views.OrganizationView.as_view(), name = "specific_org"),
    # path('orgs/<slug:org_slug>/topics/', include('topics.urls', namespace = 'topics')),
    

    # path('topics/<slug:topic_slug>/explore/', ExploreView.as_view(), name='explore'),
    # path('topics/<slug:topic_slug>/explore/post/', PostCreate.as_view(), name='create_post'),
    # path('topics/<slug:topic_slug>/explore/update', PostUpdate.as_view(), name='update_post'),
#    path('post/<int:pk>/delete/', PostDelete.as_view(), name='delete_post'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('register/org', views.RegisterOrgView.as_view(), name='org_register'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', views.logout_view, name='logout'),
    path('org_autocomplete/', views.OrgAutocomplete.as_view(), name='org_autocomplete'),
    path('<slug:username>/profile/', views.UserDetail.as_view(), name ='user_profile'),
    path('<slug:username>/profile/update/', views.UpdateProfileView.as_view(), name ='profile_update'),

]

activities/models.py
from django.db import models
from users.models import Profile
import datetime
from django.utils import timezone
from django.contrib.auth import  get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from topictag.models import TaggedObject, Tag
from taggit.managers import TaggableManager
from topics.models import Topic



User = get_user_model()

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    content = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    date_created = models.DateTimeField(verbose_name='date published', auto_now_add=True)

    # def get_absolute_url(self):
    #     return reverse('blog:post', kwargs={'pk': self.pk})

    def __str__(self):
        return '"{title}" by {username}'.format(title=self.title,
                                                username=self.user.username)



class PostComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(verbose_name='date published', auto_now_add=True)

    def __str__(self):
        return '"{content}..." on {post_title} by {username}'.format(content=self.content[:20],
                                                                  post_title=self.post.title,
                                                                  username=self.user.username)


# class ItemSchedule(models.Model):

class Blog(models.Model):
    name = models.CharField(max_length=255, unique = True,)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    tags = TaggableManager(through=TaggedObject)
    author = models.ForeignKey(User, related_name='blog_author_set', on_delete= models.CASCADE, null = True)
    # author = models.ManyToManyField(User,)

    blog_slug = models.SlugField(unique = True, blank=True)
    def save(self, *args, **kwargs):
        self.blog_slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)


    def get_tag_names(self):
        return [tag.name for tag in Tag.objects.get_for_object(self)]
    def get_absolute_url(self):
        return reverse('activities:specific_blog', kwargs={'blog_slug' : self.blog_slug})
    
class BlogComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(verbose_name='date published', auto_now_add=True)

    def __str__(self):
        return '{username}: {content}'.format(content=self.content,
                                                                  username=self.author.username)

users/models.py
# Create your models here.
# users/models.py
from django.utils import timezone
from django.urls import reverse
from django.db import models
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Count, F
from django.db.models.expressions import Func
#includes: user authen, user profile, and user acitvities
from taggit.managers import TaggableManager
from topictag.models import Tag, TaggedObject


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Users must have an email adress")
        if not password:
            raise ValueError("Users must have a password")
        if not username:
            raise ValueError("Users must have a username")

        user_obj = self.model(
            username = username,
            email = self.normalize_email(email),
            password = password
        )
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.set_password(password)
        user_obj.save(using=self._db)
        return user_obj
    def create_staffuser(self, username, email, password=None):
        user = self.create_user(
            username, email, password=password, is_staff=True
        )
        return user
    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username, email, password=password, is_staff=True, is_admin=True
        )
        return user


class User(AbstractBaseUser):
    #id, password, last_login
    username    = models.CharField(max_length = 255, unique=True)
    #demand real first and last name
    email   = models.EmailField(unique=True, max_length = 255)
    USERNAME_FIELD = 'username'
    
    timestamp = models.DateTimeField(auto_now_add=True)

    user_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    active  = models.BooleanField(default=True) #can login
    staff    = models.BooleanField(default=False)
    admin   = models.BooleanField(default=False) #superuser
    confirmed_email = models.BooleanField(default=False) #superuser
    confirmed_email_time = models.DateTimeField(auto_now_add=True)

    #

    #username_field and password are required by default
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

    def get_first_name(self):
        return self.first_name

    def is_staff(self):
        return self.staff
    def is_admin(self):
        return self.admin
    def is_active(self):
        return self.active
    def is_confirmed_email(self):
        return self.confirmed_email

    def get_absolute_url(self):
        return reverse('users:index',)

    is_member = models.BooleanField(default=False)
    is_decision_maker = models.BooleanField(default=False)


    
    
    #user_slug is username

    


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(default='', blank=True, null=True)
    bio = models.TextField(verbose_name="Biography", blank = True, null = True,) 
    first_name = models.CharField(max_length=255, blank = True, null = True)
    last_name = models.CharField(max_length=255, blank = True, null = True) 
    location_city = models.CharField(verbose_name="City living in", blank = True, null = True, max_length =255,)
    location_state = models.CharField(verbose_name="State living in", blank = True, null = True, max_length = 255,)
    location_country = models.CharField(verbose_name="Country living in", blank = True, null = True,max_length = 255,)
    def __str__(self):
        return self.user.username
    followers = models.ManyToManyField('Profile',
                                        related_name="followers_profile",
                                        blank=False,)
    following = models.ManyToManyField('Profile',
                                        related_name="following_profile",
                                        blank=False,)
    #add test: if following no one return empty
    def get_number_of_followers(self):
        if self.followers.count():
            return self.followers.count()
        else:
            return 0

    def get_number_of_following(self):
        if self.following.count():
            return self.following.count()
        else:
            return 0

    MEMBER_TYPE_CHOICES = (
        (0, 'observer'), #an observer can view deliberations of other orgs, open to all
        (1, 'member'), #an observer becoming a member gives them deliberative power, need to have profile and authentication.
        (2, 'decision maker'), #a member becoming a decision maker gives them representative duties
        (3, 'messenger'), #a member or a consultant can become a messenger that is a neutral party between member and decision maker
        (4, 'consultant'), #an observer can be invited by an outside org to be their consultant
    )
    member_type = models.PositiveSmallIntegerField(choices=MEMBER_TYPE_CHOICES, blank=True, default = 0)

    membership_validated = models.BooleanField(default=False)
    def is_membership_validated(self):
        return self.membership_validated
    
  

    MEMBER_BADGE_CHOICES = (
        (1, 'observer'), 
        (2, 'active'),
        (3, 'informed and engaged'), 
    )
    member_badge = models.PositiveSmallIntegerField(choices=MEMBER_BADGE_CHOICES, blank=True, default = 1)
    
    tags = TaggableManager(through=TaggedObject)

    def get_tag_names(self):
        return [tag.name for tag in Tag.objects.get_for_object(self)]


    # User.objects.filter(user=self).annotate(
    #                                         mrank=Func(F('posts') / 10, function 'CEIL'),
    #                                     )
    # def _get_member_badge(self):
    #     mrank = getattr(self, 'mrank', None)
    #     if mrank is None:
    #         mrank = 0
    #     return MEMBER_BADGE_CHOICES[mrank]
    # member_badge = property(_get_member_badge)

    # OBSERVER_BADGE_CHOICES = ['unfamiliar', 'familiar', 'informed',]
    # OFFICIAL_BADGE_CHOICES = ['elitist', 'representative', 'populist',]
    # MESSENGER_BADGE_CHOICES = ['unresponsive','responsive','interactive',]
    # CONSULTANT_BADGE_CHOICES = ['newly commissioned', 'contributor', 'trusted',]
    # [person.fullname for person in Person.objects.all()]
    # use this to access non-field property of model

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

#badges for regulars: regular, citizen, active citizen, informed citizen
#badges for gov officials: populist, representative, elitist
#badges for bus officials: responsive, listenner, responsible, elitist, hardliner



class UserEmail(models.Model):
    email = models.EmailField()
    active = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    update = models.DateTimeField(auto_now = True)
    timestamp= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


def upload_to(instance, filename):
    return 'images/%s/%s' % (instance.user.user.user_id, filename)
class UserAvatar(models.Model):
    avatar = models.ImageField(upload_to=upload_to)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

topics/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate
from .models import Topic, ExplorePost
from dal import autocomplete
from organizations.models import Organization



class RegisterTopicForm(forms.ModelForm):

    def __init__(self, **kwargs):
        # self.organization = kwargs.pop('user', None)
        self.organization = kwargs.pop('organization', None)
        self.topic = kwargs.pop('topic', None)
        super(RegisterTopicForm, self).__init__(**kwargs)

    class Meta:
        model = Topic
        fields = ('name','summary', )
           
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name of topic'}),
            'summary': forms.TextInput(attrs={'placeholder': 'Description of topic'}),

        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        qs = Topic.objects.filter(name=name)
        if qs.exists():
            raise forms.ValidationError("Topic may have already been registered")
        return name

    def save(self, commit=True):
        topic = super(RegisterTopicForm, self).save(commit=False)
        topic.active = True #False if archived and not current
        topic.organization = self.organization
        # topic.organization = Organization.objects.get(slug=self.kwargs['org_slug'])
        if commit:
            topic.save()
        return topic

class TopicAddTagForm(forms.Form):
    tag = forms.CharField(label='Tag', max_length=100)

class ExplorePostAddForm(forms.ModelForm):

    def __init__(self, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic = kwargs.pop('topic', None)
        super(ExplorePostAddForm, self).__init__(**kwargs)

    def save(self, commit=True):
        obj = super(ExplorePostAddForm, self).save(commit=False)
        obj.user = self.user
        obj.topic = self.topic
        if commit:
            obj.save()
        return obj
    class Meta:
        model = ExplorePost
        fields = ('content',)
        widgets = {
            'content': forms.TextInput(attrs={'placeholder': 'Content of statement'}),
        }
        #field of topic is automatically added by url and creator user

topics/templates/topics/contact.html
{% extends 'base_home.html' %}

{% block content %}
	<p style="font-size:69">CONTACT ME MAYBE!</p>
	<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>


<h3>Contact Form</h3>

<div class="container">
  <form action="/action_page.php">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

topics/templates/topics/index.html
{% extends 'base_topics.html' %}

{% block content %}
	<h1>Yo yo</h1>
	<p style="font-size:69">List of affiliated topics</p>
	<a href="{% url 'topics:register' %}">Register new topic</a>
	
	{% for topic in topics %}
    <a href="{{ topic.get_absolute_url_mod }}">{{ topic.name }}</a>
    <p>{{ topic.topic_slug }}</p>
	{% endfor %} 

{% endblock %}

topics/templates/topics/registration.html
{% extends "base_home.html" %}
{% block content %}
<!-- Form - User -->
<div id="register">
    
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
   
        </style>
        {{ form.as_p }}
        <hr>
        <button type="submit" class="registerbtn">Register</button>
        
    </form>
</div>
{% endblock content %}

topics/templates/topics/specific_topic.html
{% extends 'base_home.html' %}

{% block breadcrumb %}
<a href="{% url 'organizations:specific_org' org_slug=topic.organization.org_slug %}">{{topic.organization.name}}</a>
<a href="{% url 'organizations:specific_org_topics:org_topic' org_slug=topic.organization.org_slug topic_slug=topic.topic_slug %}">{{topic.name}}</a>

{% endblock %}

{% block content %}
<h2 style="background-color: #ffdddd;
  border-left: 6px solid #f44336;">  {{topic.name}}
</h2>
<p> 
        I do/do not support this campaign
</p>
<p>Posted date: {{ topic.created_date|date }}</p>
<p>Organization: {{ topic.organization.name }}, {{topic.organization.get_org_type_display}} </p>

<p>Relevant topics: </p>
<a href="{% url 'organizations:specific_org_tags' org_slug=topic.organization.org_slug %}">
Learn more!</a>

    <div id="tag_label">
    {% for tag in topic.tags.all %}
    <a href="#">{{ tag.name }}</a>
    {% endfor %}
    </div>

<div class="add-tag-form">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default btn-sm">Add</button>
        </form>
</div>


<br>


<h2 style="background-color: #BCD2EE;
  border-left: 6px solid blue;">Explore the matter:</h2>

<a href="explore/">Explore</a>
<button class="collapsible">Explore</button>
<div class="collapsible_content">

 {% for post in topic.topic_explore_posts.all %}
    <p>
    <div class="card">
<!--     <div class="author_chip">
 --><!--   <img src="img_avatar.png" alt="Person" width="96" height="96">
 -->  <a href="{% url 'users:user_profile' username=post.user.username %}">{{post.user.username}}<br/>{{post.user.user_membership.member_type}}<br/>{{post.user.usermembership_set.get_member_type_display}}
 {{post.user.user_membership.get_member_type_display}}derb</a>

<!-- </div> -->
<p>
    {{ post.content }}<br/>

<span>
        <button type="button" class="trans_block_btn" style="float: left; display: inline-block; background-color:red;">
        Unlike</button>
        <button type="button" class="trans_block_btn" style="float: right; display: inline-block; background-color:#4CAF50">Like</button>
</span>
</p>

    

</div>
</p>

{% endfor %}
</div>

<div class="add-explore-post-form">
        <form method="POST" class="post-form">
            {% csrf_token %}
            <p>Add explore post here:</p>
            {{ form_explore_post.as_p }}
            <button type="submit" class="save btn btn-default btn-sm">Add Explore Post</button>
        </form>
</div>


<p> Summary: {{ topic.summary }}</p>
<p>Main concerns: </p>
<p>Voices included: decision makers, constituents, professionals, etc</p>
<p>Why I'm affected: </p>
<p>Add in new conversations: email chains, posts, etc</p>
<p>Add in new documents: applications, reports, etc</p>
<h2 style="background-color: bisque;
  border-left: 6px solid orange;">What to do:</h2>
	<p>Vote?</p>
	<p>Attend meeting?</p>
	<p>Create/attend poll</p>
	<p>Submit POV--requested?</p>
	<p>Word cloud poll--relevant? Importance up</p>
<h3>Reminder list: </h3>
	<p>Upcoming events</p>
    <p>My bookmarked</p>

<h2>The POVs
</h2>
<p>Upload your story!</p>
{% for p in topic.post_set.all %}
<p>
{{ p }}:
{{ p.content }}
</p>
{% endfor %}
<a href="share-story/">Share your story</a>

<h2 style="background-color: #ffdddd;
  border-left: 6px solid #f44336;">Proposals
</h2>
<a href="outcomes/">Outcomes</a>
<p>anyone can make proposals but: depends on user reputation and title, upvotes, etc</p>
{% endblock %}

topics/templates/topics/specific_topic_explore.html
{% extends 'base_home.html' %}

{% block content %}
<h2>
    {{topic.name}}
</h2>
<p>
    tinder card in website form: ~manga pages
</p>

<br>


<h2>Explore the matter:</h2>


<div>

 {% for post in topic.topic_explore_posts.all %}
    <p>
    <div class="card">
<!--     <div class="author_chip">
 --><!--   <img src="img_avatar.png" alt="Person" width="96" height="96">
 -->  <a href="{% url 'users:user_profile' username=post.user.username %}">{{post.user.username}}<br/>{{post.user.user_membership.member_type}}<br/>{{post.user.usermembership_set.get_member_type_display}}
 {{post.user.user_membership.get_member_type_display}}derb</a>

<!-- </div> -->
    <p>
        {{ post.content }}<br/>

    <span style="z-index: 0">
            <button type="button" class="trans_block_btn" style="float: left; display: inline-block; 
            background-color:red;">
            Unlike</button>
            <button type="button" class="trans_block_btn" style="float: right; display: inline-block; background-color:#4CAF50">Like</button>
    </span>
    </p>

    

    </div>
</p>

{% endfor %}
</div>

<div class="add-explore-post-form">
        <form method="POST" class="post-form">
            {% csrf_token %}
            <p>Add explore post here:</p>
            {{ form_explore_post.as_p }}
            <button type="submit" class="save btn btn-default btn-sm">Add Explore Post</button>
        </form>
</div>

{% endblock %}

topics/templates/topics/specific_topic_outcomes.html
{% extends 'base_home.html' %}

{% block content %}

<h2 style="background-color: #ffdddd;
  border-left: 6px solid #f44336;">Possible proposals</h2>

<div class="outcome_columns">
  <ul class="outcome">
    <li class="header">Basic</li>
    <li class="grey">$ 9.99 / year</li>
    <li>10GB Storage</li>
    <li>10 Emails</li>
    <li>10 Domains</li>
    <li>1GB Bandwidth</li>
    <li class="grey"><a href="#" class="button">Sign Up</a></li>
  </ul>
</div>

{% endblock %}