DeliX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('home.urls', namespace='home')),
    path('orgs/', include('organizations.urls', namespace='organizations')),
    path('topics/', include('topics.urls', namespace='topics')),
    path('activities/',include('activities.urls', namespace='activities')),
    path('select2/', include('django_select2.urls')),
     ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('home/', views.index, name='index'),

]

organizations/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.decorators import login_required

app_name = "organizations"

urlpatterns = [
    # path('', views.IndexView.as_view(), name='<slug>.index'),

    path('', views.index, name = "index"),
    path('register/new_org/', views.RegisterView.as_view(), name = "register"),
    #path('<slug:org_slug>/', views.specific_org, name = "specific_org"),
    path('<slug:org_slug>/', views.OrgDetail.as_view(), name = "specific_org"),

    #to detail of tags
    path('<slug:org_slug>/tags/', views.OrgTagList.as_view(), name = "specific_org_tags"),

    path('<slug:org_slug>/', include('topics.urls', namespace = "specific_org_topics")),

    path('<slug:org_slug>/campaigns/', include('campaign.urls', namespace = 'org_campaigns')),
    path('<slug:org_slug>/join/', login_required(views.join), name='join'),
    ]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('register/org', views.RegisterOrgView.as_view(), name='org_register'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', views.logout_view, name='logout'),
    path('org_autocomplete/', views.OrgAutocomplete.as_view(), name='org_autocomplete'),
    path('<slug:username>/profile/', views.UserDetail.as_view(), name ='user_profile'),
    path('<slug:username>/profile/update/', views.UpdateProfileView.as_view(), name ='profile_update'),

]

users/models.py
# Create your models here.
# users/models.py
from django.utils import timezone
from django.urls import reverse
from django.db import models
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
import uuid
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Count, F
from django.db.models.expressions import Func
#includes: user authen, user profile, and user acitvities
from taggit.managers import TaggableManager
from topictag.models import Tag, TaggedObject


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Users must have an email adress")
        if not password:
            raise ValueError("Users must have a password")
        if not username:
            raise ValueError("Users must have a username")

        user_obj = self.model(
            username = username,
            email = self.normalize_email(email),
            password = password
        )
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.set_password(password)
        user_obj.save(using=self._db)
        return user_obj
    def create_staffuser(self, username, email, password=None):
        user = self.create_user(
            username, email, password=password, is_staff=True
        )
        return user
    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username, email, password=password, is_staff=True, is_admin=True
        )
        return user


class User(AbstractBaseUser):
    #id, password, last_login
    username    = models.CharField(max_length = 255, unique=True)
    #demand real first and last name
    email   = models.EmailField(unique=True, max_length = 255)
    USERNAME_FIELD = 'username'
    
    timestamp = models.DateTimeField(auto_now_add=True)

    user_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    active  = models.BooleanField(default=True) #can login
    staff    = models.BooleanField(default=False)
    admin   = models.BooleanField(default=False) #superuser
    confirmed_email = models.BooleanField(default=False) #superuser
    confirmed_email_time = models.DateTimeField(auto_now_add=True)

    #

    #username_field and password are required by default
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

    def get_first_name(self):
        return self.first_name

    def is_staff(self):
        return self.staff
    def is_admin(self):
        return self.admin
    def is_active(self):
        return self.active
    def is_confirmed_email(self):
        return self.confirmed_email

    def get_absolute_url(self):
        return reverse('users:index',)

    is_member = models.BooleanField(default=False)
    is_decision_maker = models.BooleanField(default=False)


    
    
    #user_slug is username

    


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(default='', blank=True, null=True)
    bio = models.TextField(verbose_name="Biography", blank = True, null = True,) 
    first_name = models.CharField(max_length=255, blank = True, null = True)
    last_name = models.CharField(max_length=255, blank = True, null = True) 
    location_city = models.CharField(verbose_name="City living in", blank = True, null = True, max_length =255,)
    location_state = models.CharField(verbose_name="State living in", blank = True, null = True, max_length = 255,)
    location_country = models.CharField(verbose_name="Country living in", blank = True, null = True,max_length = 255,)
    def __str__(self):
        return self.user.username
    followers = models.ManyToManyField('Profile',
                                        related_name="followers_profile",
                                        blank=False,)
    following = models.ManyToManyField('Profile',
                                        related_name="following_profile",
                                        blank=False,)
    #add test: if following no one return empty
    def get_number_of_followers(self):
        if self.followers.count():
            return self.followers.count()
        else:
            return 0

    def get_number_of_following(self):
        if self.following.count():
            return self.following.count()
        else:
            return 0

    MEMBER_TYPE_CHOICES = (
        (0, 'observer'), #an observer can view deliberations of other orgs, open to all
        (1, 'member'), #an observer becoming a member gives them deliberative power, need to have profile and authentication.
        (2, 'decision maker'), #a member becoming a decision maker gives them representative duties
        (3, 'messenger'), #a member or a consultant can become a messenger that is a neutral party between member and decision maker
        (4, 'consultant'), #an observer can be invited by an outside org to be their consultant
    )
    member_type = models.PositiveSmallIntegerField(choices=MEMBER_TYPE_CHOICES, blank=True, default = 0)

    membership_validated = models.BooleanField(default=False)
    def is_membership_validated(self):
        return self.membership_validated
    
  

    MEMBER_BADGE_CHOICES = (
        (1, 'observer'), 
        (2, 'active'),
        (3, 'informed and engaged'), 
    )
    member_badge = models.PositiveSmallIntegerField(choices=MEMBER_BADGE_CHOICES, blank=True, default = 1)
    
    tags = TaggableManager(through=TaggedObject)

    def get_tag_names(self):
        return [tag.name for tag in Tag.objects.get_for_object(self)]


    # User.objects.filter(user=self).annotate(
    #                                         mrank=Func(F('posts') / 10, function 'CEIL'),
    #                                     )
    # def _get_member_badge(self):
    #     mrank = getattr(self, 'mrank', None)
    #     if mrank is None:
    #         mrank = 0
    #     return MEMBER_BADGE_CHOICES[mrank]
    # member_badge = property(_get_member_badge)

    # OBSERVER_BADGE_CHOICES = ['unfamiliar', 'familiar', 'informed',]
    # OFFICIAL_BADGE_CHOICES = ['elitist', 'representative', 'populist',]
    # MESSENGER_BADGE_CHOICES = ['unresponsive','responsive','interactive',]
    # CONSULTANT_BADGE_CHOICES = ['newly commissioned', 'contributor', 'trusted',]
    # [person.fullname for person in Person.objects.all()]
    # use this to access non-field property of model

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

#badges for regulars: regular, citizen, active citizen, informed citizen
#badges for gov officials: populist, representative, elitist
#badges for bus officials: responsive, listenner, responsible, elitist, hardliner



class UserEmail(models.Model):
    email = models.EmailField()
    active = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    update = models.DateTimeField(auto_now = True)
    timestamp= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


def upload_to(instance, filename):
    return 'images/%s/%s' % (instance.user.user.user_id, filename)
class UserAvatar(models.Model):
    avatar = models.ImageField(upload_to=upload_to)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.utils.http import is_safe_url
from django.views.generic import CreateView, FormView, DetailView, ListView, UpdateView
#from topics.models import Topic
User = get_user_model()
from .forms import loginform, RegisterForm, ProfileForm, FollowForm, UserAddTagForm
from .models import Profile
from organizations.models import Organization
from dal.autocomplete import Select2QuerySetView


class OrgAutocomplete(Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor 's permission!
        if not self.request.user.is_authenticated():
            return Organization.objects.none()
        qs = Organization.objects.all()

        qs = qs.filter(
                           usermembership_set__is = self.request.user, #suspect!!!! but important for security reasons
            )

        return qs


class RegisterView(CreateView):
   form_class = RegisterForm
   template_name = "users/registration.html"
   success_url = reverse_lazy('users:login')
   context = {
      'form': RegisterForm()
   }
class UpdateProfileView(UpdateView):
    def is_authen(self):
        if not request.user.is_authenticated():
            redirect('users:login')
    form_class = ProfileForm
    model = Profile
    template_name = 'users/profile_update.html'
    def get_success_url(self):
        return reverse('users:user_profile', kwargs={'username': self.kwargs.get('username')})
    def get_object(self, queryset=None):
        obj = Profile.objects.get(user = self.request.user)
        return obj


class LoginView(FormView):
   form_class = loginform
   # success_url = reverse_lazy('users:index')
   template_name = "users/login.html"
   def form_valid(self,form):
       request = self.request
       next_ = request.GET.get('next')
       next_post = request.POST.get('next')
       #redirect_path = next_ or next_post or None
       redirect_path = reverse_lazy('users:index')
       username = form.cleaned_data.get("username")
       password = form.cleaned_data.get("password")
       user = authenticate(request, username=username, password=password)

       if user is not None:
          if user.is_active:
             login(request, user)
          try:
             del request.session['guest_email_id']
          except:
             pass
          if is_safe_url(redirect_path, request.get_host()):
             return redirect(redirect_path)
          else:
             return redirect("/")
       return super(LoginView, self).form_invalid(form)
#
def logout_view(request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('users:index'))

def index(request):
    def get_queryset(self):
        queryset = self.request.user
        return queryset

    def post(self, request, *args, **kwargs):
        form = UserAddTagForm(request.POST)
        if form.is_valid():
            user.tags.add(form.cleaned_data['new_tag'])
        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        context = {
                   'form': UserAddTagForm(),
                   }
        return context
    return render(request, 'users/index.html')


class IndexView(ListView):
    template_name = 'users/index.html'
    #queryset = Topic.objects.all()
    #model = Topic
    #paginate_by = 10
    #ordering = ['-created_date']
    # if use this comment out model = Topic and add context_object_name
    context_object_name = "topics"
    def get_queryset(self):
        queryset = (Topic.objects
                    .all()
                    .order_by('-created_date'))
        # queryset = Topic.objects.all().prefetch_related('bids').filter(user=self.request.user)) #uncomment model = Topic
        #
        return queryset


class UserDetail(DetailView):
    model = User

    # def get_success_url(self):
    #     return reverse('organizations:specific_org_topics:org_topic',
    #                    kwargs={'topic_slug': self.topic_slug, 'org_slug': self.organization.org_slug})

    template_name = "users/specific_user.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        return self.render_to_response(self.get_context_data())

        form_follow = FollowForm()
        if form_follow.is_valid():
            form_follow.save()
        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        username = self.kwargs.get('username') #get username from url using self.kwargs.get(), only works inside a def inside class
        self.object = self.get_object()
        context = super(UserDetail, self).get_context_data(**kwargs)

        context = {'specific_user': User.objects.get(username=username),
                    'form_follow': FollowForm(),
                   }
        return context

users/templates/users/index.html
{% extends 'base_home.html' %}

{% block headingbar-right %}

{% if user.is_authenticated %}
<a href="{% url 'users:logout' %}">Logout</a>
{% endif %}

{% endblock %}

{% block content %}



{% if user.is_authenticated %}
Hi {{ user.username }}!
<a href = "{% url 'users:user_profile' username=user.username %}">My profile</a>
	
<p>My organizations: </p>


{% for o in user.orgs.all %}
	<a href="{% url 'organizations:specific_org' org_slug=o.org_slug %}">{{ o.name }}
	</a>
	<p> {{o.summary}}
	</p>

{% endfor %}
<p>
		Following events:
	</p>
{% for t in user.profile.tags.all %}

{% endfor %}
<div class="add-tag-form">
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default btn-sm">Add</button>
        </form>
    </div>
{% else %}
<button class="button"><span><a href="{% url 'users:register' %}">Register</a></span></button>
<button class="button"><span><a href="{% url 'users:login' %}">Login</a></span></button>
<p>
		<button class="button"><span><a href="{% url 'organizations:index' %}">All organizations</a></span></button>
	
</p>
<p>
	Popular topics:
</p>


{% endif %}




{% endblock %}

users/templates/users/login.html
{% extends "base_home.html" %}
{% block content %}




<form action="" method="post" class="form-horizontal">
    {% csrf_token %}
    
    {{ form.as_p }}
    <button type="submit" class="loginbtn" value='login'>Log in</button>
    <hr>
</form>
{% endblock %}

users/templates/users/org_registration.html
{% extends "base_home.html" %}
{% block content %}
<!-- Form - User -->
<div id="register">

    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}

        </style>
        {{ form.as_p }}
        <hr>
        <button type="submit" class="registerbtn">Register Organization</button>
        <p>You'd still need to wait for verification from your organization</p>
    </form>
</div>
{% endblock content %}

users/templates/users/profile_update.html
{% extends "base_home.html" %}
{% block content %}
<!-- Form - User -->
<div id="register">

    <form action="" method="POST" class="form-horizontal">
        {% csrf_token %}

        {{ form.as_p }}
        <hr> 
        <button type="submit" class="registerbtn">Update Profile</button>
    </form>
</div>
{% endblock content %}

users/templates/users/registration.html
{% extends "base_home.html" %}
{% block content %}
<!-- Form - User -->
<div id="register">
    
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
   
        </style>
        {{ form.as_p }}
        <hr>
        <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
        <button type="submit" class="registerbtn">Register</button>
        <div class="container signin">
            <p>Already have an account? <a href="{% url 'users:login' %}">Log in</a>.</p>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/specific_user.html
{% extends 'base_home.html' %}

{% block content %}
<h2>
    {{profile.user.username}}
</h2>
<ul>
    <li>
        username: {{ specific_user.email }}
    </li>
    <li>
        First name: {{ specific_user.profile.first_name }}
    </li>
    <li>
        Last name: {{ specific_user.profile.last_name }}
    </li>
    <li>
        Date joined: {{ specific_user.time_stamp }}
    </li>
    <li>
        Member of organizations: 
        {% for o in specific_user.orgs.all %}
        <a href="{% url 'organizations:specific_org' org_slug=o.org_slug %}">{{ o.name }}
        </a>        
        {% endfor %}
    </li>
    <li>
        Biography: {{ specific_user.profile.bio }}
    </li>
   <li>
       Badge: {{ specific_user.profile.get_member_badge_display}}
   </li>
   
    
</ul>

<a href="update/">Update Profile</a>

<form action="" method="post" class="form-horizontal">
        {% csrf_token %}

        </style>
        {{ form_follow.as_p }}
        <hr>
        <button type="submit" class="registerbtn">Follow</button>
    </form>
{% endblock %}